export const ENTRIES_DISABLED = false;
export const THEORETICAL_PORTFOLIO_SIZE = 1_000_000;
export const MAX_PURCHASE_AMOUNT = THEORETICAL_PORTFOLIO_SIZE * 0.02;
export const PRICE_WIGGLE_ROOM_PERCENT = 0.005;
export const IS_PAPER_TRADING = false;
export const EXIT_BLACK_LIST = ["WBA", "SQ"];
